[tool.poetry]
name = "push-receiver"
version = "0.1.0"
description = "FCM/GCM push notification receiver\u001b[D\u001b[D\u001b[D\u001b[D\u001b[D\u001b["
authors = ["sdb9696 <steven.beth@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
oscrypto = "^1.3.0"
protobuf = "^4.24.4"
cryptography = "^41.0.4"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
flake8 = "*"
pre-commit = "*"
tox = "*"
black = "*"
pylint = "^3.0.1"
isort = "^5.12.0"
pytest = "^7.4.2"
pytest-mock = "^3.11.1"
requests-mock = "^1.11.0"

[tool.isort]
profile = "black"
known_first_party = "push_receiver"
known_third_party = ["asyncclick", "setuptools"]

[tool.pylint]
disable = ["missing-module-docstring", "missing-function-docstring", 
"missing-class-docstring",
"broad-exception-caught",
"consider-using-f-string",
]
overgeneral-exceptions = ["builtins.Exception"]
ignore-paths = ["push_receiver/proto", "push_receiver/decrypt.py", "tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
